{% set version = "1.15.1.post20240724" %}

package:
  name: libquickfix
  version: {{ version|replace("-", "_") }}

source:
  url: https://github.com/quickfix/quickfix/archive/94625580bfd50c1ebba3f704a88c9e3c392f9fb1.zip
  sha256: 9d4b3f16150af235fbbff937f76665d263fa7555f39e70007ec1e464f9400ade
  patches:
    - remove_net_test.diff

build:
  number: 3
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('libquickfix', max_pin='x.x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - libtool
    - m4
    - autoconf
    - automake
    - make
  host:
    - libtool
    - mysql-server

test:
  commands:
    - test -f ${PREFIX}/include/quickfix/config.h
    - test -f ${PREFIX}/lib/libquickfix${SHLIB_EXT}

about:
  home: https://github.com/quickfix/quickfix/
  license: Apache-1.1
  license_family: Apache
  license_file: LICENSE
  summary: |
    The Financial Information Exchange (FIX) Protocol is a message standard 
    developed to facilitate the electronic exchange of information related 
    to securities transactions. It is intended for use between trading 
    partners wishing to automate communications.

    QuickFIX is a free and open source implementation of the FIX protocol.

extra:
  recipe-maintainers:
    - timkpaine
    - dillonroach
